 - hosts: nodes
   tasks:
   - package:
       name: "httpd"
       state: present
   - copy:
       src: "na.html"
       dest: "/var/www/html"
   - service:
       name: "httpd"
       state: started


